import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f6f3f2',
        'primary-container': '#0f6e56',
        'on-error': '#ffffff',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'surface-container': '#f0eded',
        'primary-fixed-dim': '#84d6b9',
        'on-tertiary-fixed-variant': '#00513d',
        'on-primary-fixed-variant': '#00513e',
        'on-secondary-fixed-variant': '#693c00',
        'secondary-container': '#feb56b',
        'surface-variant': '#e5e2e1',
        'on-tertiary-fixed': '#002117',
        'surface-dim': '#dcd9d9',
        'on-secondary': '#ffffff',
        'background': '#fcf9f8',
        'secondary': '#88520e',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#8af7cf',
        'on-tertiary-container': '#85f1ca',
        'outline-variant': '#bec9c3',
        'on-primary-fixed': '#002117',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#2d1600',
        'outline': '#6f7a74',
        'secondary-fixed-dim': '#ffb870',
        'tertiary-fixed-dim': '#6edab4',
        'on-primary': '#ffffff',
        'secondary-fixed': '#ffdcbe',
        'surface-container-lowest': '#ffffff',
        'error': '#ba1a1a',
        'on-secondary-container': '#774400',
        'surface-container-highest': '#e5e2e1',
        'primary-fixed': '#a0f3d4',
        'tertiary': '#00543f',
        'surface-container-high': '#eae7e7',
        'surface': '#fcf9f8',
        'tertiary-container': '#006f54',
        'on-surface-variant': '#3f4944',
        'on-primary-container': '#9aedcf',
        'surface-tint': '#086b53',
        'on-surface': '#1c1b1b',
        'surface-bright': '#fcf9f8',
        'on-error-container': '#93000a',
        'primary': '#005440',
        'inverse-primary': '#84d6b9',
        'on-background': '#1c1b1b',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'xl': '80px',
        'base': '8px',
        'xs': '4px',
        'lg': '48px',
        'gutter': '24px',
        'md': '24px',
        'sm': '12px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'body-md': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'label-mono': ['JetBrains Mono'],
        'caption': ['Plus Jakarta Sans'],
        'headline-xl': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
export default config
